services:
  bookstore-api:
    image: bookstore
    build:
      context: .
      dockerfile: BookStore.API/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:latest
    container_name: bookstore-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db

volumes:
  postgres:
    name: bookstore-pgdata